### ISSUE TITLE
startCollapsed does not work if I have more than one aCollapTable in a page

### ISSUE THREAD

**Issue by ktllo** [alvaroveliz/aCollapTable#7]
If I have more than one aCollapTable in a page and set it to be startCollapsed. When tested with 2 table, only the last table is collapsed.

**Comment by alvaroveliz** [comment]
Have you tried to use `id` instead of `class`?

```
$('#table-id').aCollapTable();
```

**Comment by ktllo** [comment]
I am using id currently. I have to set the first one with `startCollapsed: false` and the second one with `startCollapsed: true`

**Comment by alvaroveliz** [comment]
@ktllo Please try with version `1.0.4`
